/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Energy-Efficient CPU Scheduling Algorithm API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Get all processes in the queue
 */
export const ListProcessesResponseItem = zod.object({
  id: zod.string(),
  name: zod.string(),
  priority: zod.enum(["low", "normal", "high", "realtime"]),
  state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
  burstTime: zod.number().describe("Total CPU burst time required (ms)"),
  remainingTime: zod.number().describe("Remaining burst time (ms)"),
  arrivalTime: zod.number(),
  waitingTime: zod.number(),
  turnaroundTime: zod.number(),
  powerWeight: zod.number().describe("Process power consumption weight (0-1)"),
  thermalSensitive: zod
    .boolean()
    .describe("Whether process is sensitive to thermal throttling"),
  completedAt: zod.number().nullish(),
});
export const ListProcessesResponse = zod.array(ListProcessesResponseItem);

/**
 * @summary Add a new process to the queue
 */
export const CreateProcessBody = zod.object({
  name: zod.string(),
  priority: zod.enum(["low", "normal", "high", "realtime"]),
  burstTime: zod.number(),
  powerWeight: zod.number(),
  thermalSensitive: zod.boolean(),
});

/**
 * @summary Remove a process from the queue
 */
export const DeleteProcessParams = zod.object({
  id: zod.coerce.string(),
});

export const DeleteProcessResponse = zod.object({
  id: zod.string(),
  name: zod.string(),
  priority: zod.enum(["low", "normal", "high", "realtime"]),
  state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
  burstTime: zod.number().describe("Total CPU burst time required (ms)"),
  remainingTime: zod.number().describe("Remaining burst time (ms)"),
  arrivalTime: zod.number(),
  waitingTime: zod.number(),
  turnaroundTime: zod.number(),
  powerWeight: zod.number().describe("Process power consumption weight (0-1)"),
  thermalSensitive: zod
    .boolean()
    .describe("Whether process is sensitive to thermal throttling"),
  completedAt: zod.number().nullish(),
});

/**
 * @summary Get current scheduler state
 */
export const GetSchedulerStateResponse = zod.object({
  currentTime: zod.number(),
  algorithm: zod.enum([
    "fcfs",
    "sjf",
    "priority",
    "round_robin",
    "energy_aware",
    "thermal_aware",
  ]),
  runningProcess: zod
    .object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    })
    .nullish(),
  readyQueue: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    }),
  ),
  completedProcesses: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    }),
  ),
  isRunning: zod.boolean(),
  config: zod.object({
    algorithm: zod.enum([
      "fcfs",
      "sjf",
      "priority",
      "round_robin",
      "energy_aware",
      "thermal_aware",
    ]),
    timeQuantum: zod.number().describe("Time quantum for round-robin (ms)"),
    dvfsEnabled: zod.boolean(),
    thermalThrottle: zod.boolean(),
    powerBudget: zod
      .number()
      .describe("Max allowed power consumption in Watts"),
  }),
});

/**
 * @summary Update scheduler algorithm and configuration
 */
export const UpdateSchedulerConfigBody = zod.object({
  algorithm: zod.enum([
    "fcfs",
    "sjf",
    "priority",
    "round_robin",
    "energy_aware",
    "thermal_aware",
  ]),
  timeQuantum: zod.number().describe("Time quantum for round-robin (ms)"),
  dvfsEnabled: zod.boolean(),
  thermalThrottle: zod.boolean(),
  powerBudget: zod.number().describe("Max allowed power consumption in Watts"),
});

export const UpdateSchedulerConfigResponse = zod.object({
  algorithm: zod.enum([
    "fcfs",
    "sjf",
    "priority",
    "round_robin",
    "energy_aware",
    "thermal_aware",
  ]),
  timeQuantum: zod.number().describe("Time quantum for round-robin (ms)"),
  dvfsEnabled: zod.boolean(),
  thermalThrottle: zod.boolean(),
  powerBudget: zod.number().describe("Max allowed power consumption in Watts"),
});

/**
 * @summary Advance scheduler by one time unit
 */
export const TickSchedulerResponse = zod.object({
  schedulerState: zod.object({
    currentTime: zod.number(),
    algorithm: zod.enum([
      "fcfs",
      "sjf",
      "priority",
      "round_robin",
      "energy_aware",
      "thermal_aware",
    ]),
    runningProcess: zod
      .object({
        id: zod.string(),
        name: zod.string(),
        priority: zod.enum(["low", "normal", "high", "realtime"]),
        state: zod.enum([
          "ready",
          "running",
          "waiting",
          "completed",
          "blocked",
        ]),
        burstTime: zod.number().describe("Total CPU burst time required (ms)"),
        remainingTime: zod.number().describe("Remaining burst time (ms)"),
        arrivalTime: zod.number(),
        waitingTime: zod.number(),
        turnaroundTime: zod.number(),
        powerWeight: zod
          .number()
          .describe("Process power consumption weight (0-1)"),
        thermalSensitive: zod
          .boolean()
          .describe("Whether process is sensitive to thermal throttling"),
        completedAt: zod.number().nullish(),
      })
      .nullish(),
    readyQueue: zod.array(
      zod.object({
        id: zod.string(),
        name: zod.string(),
        priority: zod.enum(["low", "normal", "high", "realtime"]),
        state: zod.enum([
          "ready",
          "running",
          "waiting",
          "completed",
          "blocked",
        ]),
        burstTime: zod.number().describe("Total CPU burst time required (ms)"),
        remainingTime: zod.number().describe("Remaining burst time (ms)"),
        arrivalTime: zod.number(),
        waitingTime: zod.number(),
        turnaroundTime: zod.number(),
        powerWeight: zod
          .number()
          .describe("Process power consumption weight (0-1)"),
        thermalSensitive: zod
          .boolean()
          .describe("Whether process is sensitive to thermal throttling"),
        completedAt: zod.number().nullish(),
      }),
    ),
    completedProcesses: zod.array(
      zod.object({
        id: zod.string(),
        name: zod.string(),
        priority: zod.enum(["low", "normal", "high", "realtime"]),
        state: zod.enum([
          "ready",
          "running",
          "waiting",
          "completed",
          "blocked",
        ]),
        burstTime: zod.number().describe("Total CPU burst time required (ms)"),
        remainingTime: zod.number().describe("Remaining burst time (ms)"),
        arrivalTime: zod.number(),
        waitingTime: zod.number(),
        turnaroundTime: zod.number(),
        powerWeight: zod
          .number()
          .describe("Process power consumption weight (0-1)"),
        thermalSensitive: zod
          .boolean()
          .describe("Whether process is sensitive to thermal throttling"),
        completedAt: zod.number().nullish(),
      }),
    ),
    isRunning: zod.boolean(),
    config: zod.object({
      algorithm: zod.enum([
        "fcfs",
        "sjf",
        "priority",
        "round_robin",
        "energy_aware",
        "thermal_aware",
      ]),
      timeQuantum: zod.number().describe("Time quantum for round-robin (ms)"),
      dvfsEnabled: zod.boolean(),
      thermalThrottle: zod.boolean(),
      powerBudget: zod
        .number()
        .describe("Max allowed power consumption in Watts"),
    }),
  }),
  dvfsState: zod.object({
    currentPState: zod.number(),
    frequency: zod.number().describe("Current frequency in GHz"),
    voltage: zod.number().describe("Current voltage in Volts"),
    currentPower: zod.number().describe("Current power consumption in Watts"),
    powerBudget: zod.number().describe("Max power budget in Watts"),
    utilizationPercent: zod.number().describe("CPU utilization 0-100"),
    dvfsEnabled: zod.boolean(),
  }),
  thermalState: zod.object({
    temperature: zod.number().describe("CPU temperature in Celsius"),
    zone: zod.enum(["safe", "warm", "hot", "critical"]),
    throttled: zod.boolean(),
    throttlePercent: zod
      .number()
      .describe("Performance reduction from thermal throttling (0-100)"),
    fanSpeed: zod.number().describe("Fan speed percent (0-100)"),
    maxTemperature: zod.number(),
    minTemperature: zod.number(),
  }),
  metrics: zod.object({
    avgWaitingTime: zod.number(),
    avgTurnaroundTime: zod.number(),
    throughput: zod.number().describe("Processes completed per time unit"),
    cpuUtilization: zod.number().describe("CPU utilization percent 0-100"),
    totalPowerConsumed: zod
      .number()
      .describe("Total energy consumed in Joules"),
    avgPowerWatts: zod.number(),
    energyEfficiencyScore: zod
      .number()
      .describe("Ratio of work done per unit energy (higher is better)"),
    fairnessIndex: zod
      .number()
      .describe("Jain fairness index (0-1, 1 is perfectly fair)"),
    processesCompleted: zod.number(),
    processesInQueue: zod.number(),
  }),
  event: zod
    .string()
    .nullish()
    .describe("Human-readable description of what happened this tick"),
});

/**
 * @summary Reset scheduler to initial state
 */
export const ResetSchedulerResponse = zod.object({
  currentTime: zod.number(),
  algorithm: zod.enum([
    "fcfs",
    "sjf",
    "priority",
    "round_robin",
    "energy_aware",
    "thermal_aware",
  ]),
  runningProcess: zod
    .object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    })
    .nullish(),
  readyQueue: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    }),
  ),
  completedProcesses: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      priority: zod.enum(["low", "normal", "high", "realtime"]),
      state: zod.enum(["ready", "running", "waiting", "completed", "blocked"]),
      burstTime: zod.number().describe("Total CPU burst time required (ms)"),
      remainingTime: zod.number().describe("Remaining burst time (ms)"),
      arrivalTime: zod.number(),
      waitingTime: zod.number(),
      turnaroundTime: zod.number(),
      powerWeight: zod
        .number()
        .describe("Process power consumption weight (0-1)"),
      thermalSensitive: zod
        .boolean()
        .describe("Whether process is sensitive to thermal throttling"),
      completedAt: zod.number().nullish(),
    }),
  ),
  isRunning: zod.boolean(),
  config: zod.object({
    algorithm: zod.enum([
      "fcfs",
      "sjf",
      "priority",
      "round_robin",
      "energy_aware",
      "thermal_aware",
    ]),
    timeQuantum: zod.number().describe("Time quantum for round-robin (ms)"),
    dvfsEnabled: zod.boolean(),
    thermalThrottle: zod.boolean(),
    powerBudget: zod
      .number()
      .describe("Max allowed power consumption in Watts"),
  }),
});

/**
 * @summary Get current DVFS state and frequency/voltage levels
 */
export const GetDvfsStateResponse = zod.object({
  currentPState: zod.number(),
  frequency: zod.number().describe("Current frequency in GHz"),
  voltage: zod.number().describe("Current voltage in Volts"),
  currentPower: zod.number().describe("Current power consumption in Watts"),
  powerBudget: zod.number().describe("Max power budget in Watts"),
  utilizationPercent: zod.number().describe("CPU utilization 0-100"),
  dvfsEnabled: zod.boolean(),
});

/**
 * @summary Get available P-states (frequency/voltage levels)
 */
export const GetDvfsLevelsResponseItem = zod.object({
  level: zod.number(),
  frequency: zod.number().describe("CPU frequency in GHz"),
  voltage: zod.number().describe("CPU voltage in Volts"),
  powerFactor: zod.number().describe("Power consumption relative factor (0-1)"),
  performanceFactor: zod.number().describe("Performance relative factor (0-1)"),
});
export const GetDvfsLevelsResponse = zod.array(GetDvfsLevelsResponseItem);

/**
 * @summary Get CPU thermal state
 */
export const GetThermalStateResponse = zod.object({
  temperature: zod.number().describe("CPU temperature in Celsius"),
  zone: zod.enum(["safe", "warm", "hot", "critical"]),
  throttled: zod.boolean(),
  throttlePercent: zod
    .number()
    .describe("Performance reduction from thermal throttling (0-100)"),
  fanSpeed: zod.number().describe("Fan speed percent (0-100)"),
  maxTemperature: zod.number(),
  minTemperature: zod.number(),
});

/**
 * @summary Get temperature history over last N ticks
 */
export const GetThermalHistoryResponseItem = zod.object({
  tick: zod.number(),
  temperature: zod.number(),
  zone: zod.enum(["safe", "warm", "hot", "critical"]),
  power: zod.number(),
});
export const GetThermalHistoryResponse = zod.array(
  GetThermalHistoryResponseItem,
);

/**
 * @summary Get performance and power summary metrics
 */
export const GetMetricsSummaryResponse = zod.object({
  avgWaitingTime: zod.number(),
  avgTurnaroundTime: zod.number(),
  throughput: zod.number().describe("Processes completed per time unit"),
  cpuUtilization: zod.number().describe("CPU utilization percent 0-100"),
  totalPowerConsumed: zod.number().describe("Total energy consumed in Joules"),
  avgPowerWatts: zod.number(),
  energyEfficiencyScore: zod
    .number()
    .describe("Ratio of work done per unit energy (higher is better)"),
  fairnessIndex: zod
    .number()
    .describe("Jain fairness index (0-1, 1 is perfectly fair)"),
  processesCompleted: zod.number(),
  processesInQueue: zod.number(),
});

/**
 * @summary Get historical metrics over time
 */
export const GetMetricsHistoryResponseItem = zod.object({
  tick: zod.number(),
  power: zod.number(),
  utilization: zod.number(),
  temperature: zod.number(),
  frequency: zod.number(),
  processesRunning: zod.number(),
});
export const GetMetricsHistoryResponse = zod.array(
  GetMetricsHistoryResponseItem,
);

/**
 * @summary Compare performance across scheduling algorithms
 */
export const GetAlgorithmComparisonResponseItem = zod.object({
  algorithm: zod.enum([
    "fcfs",
    "sjf",
    "priority",
    "round_robin",
    "energy_aware",
    "thermal_aware",
  ]),
  algorithmName: zod.string(),
  avgWaitingTime: zod.number(),
  avgTurnaroundTime: zod.number(),
  energyEfficiency: zod.number(),
  fairnessIndex: zod.number(),
  throughput: zod.number(),
});
export const GetAlgorithmComparisonResponse = zod.array(
  GetAlgorithmComparisonResponseItem,
);
